config/routes.rb
Rails.application.routes.draw do
  get 'checkouts/create'
  get 'order_items/update'
  root 'home#index'

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'

  resources :products, only: [:index, :show] do
    collection do
      get 'on_sale', to: 'products#on_sale', as: 'on_sale'
      get 'new_products', to: 'products#new_products', as: 'new_products'
    end
    get 'show_category/:id', to: 'products#show_category', on: :member, as: :show_category
    get 'show_product/:id', to: 'products#show', on: :member, as: :show_product
    get 'search', on: :collection
  end

  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    get 'new_product', to: 'admins#new_product', as: 'new_product'
    post 'create_product', to: 'admins#create_product', as: 'create_product'
    get 'edit_product/:id', to: 'admins#edit_product', as: 'edit_product'
    patch 'update_product/:id', to: 'admins#update_product', as: 'update_product'
    delete 'delete_product/:id', to: 'admins#delete_product', as: 'delete_product'
    get 'edit_about', to: 'admins#edit_about', as: 'edit_about_admin'
    patch 'update_about', to: 'admins#update_about', as: 'update_about_admin'
  end

  post 'add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  resource :cart, only: [:show, :create, :destroy] do
    resources :order_items, only: [:destroy, :update], as: 'items', path: 'items'
  end
  delete 'remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  scope '/checkouts' do
  post 'create', to: 'checkouts#create', as: 'create_checkout'
  get 'success', to: 'checkouts#success', as: 'checkout_success'
  get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
  end
  get 'about', to: 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true

  has_one_attached :image
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  accepts_nested_attributes_for :categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_many :order_items, through: :orders
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :country, presence: true
  validates :province, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :street_address, presence: true
  def admin?
    admin
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @logged_in = logged_in?
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/_form.html.erb
<div class="edit-form-container">
  <%= form_with(model: [:admin, product], local: true, url: (@product.persisted? ? admin_update_product_path(@product) : admin_create_product_path), method: (@product.persisted? ? :patch : :post)) do |form| %>

    <div class="form-group">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= form.label :price, class: 'form-label' %>
      <%= form.number_field :price, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= form.label :categories, 'Select or add categories', class: 'form-label' %>
      <%= form.collection_select :category_ids, Category.all, :id, :name, { prompt: 'Select or add categories', multiple: true, class: 'form-input' }, {} %>
    </div>

    <div class="form-group">
      <%= form.label :new_category_name, 'Add a new category', class: 'form-label' %>
      <%= form.text_field :new_category_name, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= form.label :image, class: 'form-label' %>
      <%= form.file_field :image, class: 'form-file-input' %>
    </div>

    <div class="form-group">
      <%= form.submit 'Save Product', class: 'form-button' %>
    </div>
  <% end %>
</div>

app/views/admin/admins/edit_about.html.erb
<h1>Edit About Information</h1>

<%= form_tag admin_update_about_path, method: :patch do %>
  <div>
    <%= label_tag :about_text, 'About Text' %>
    <%= text_area_tag :about_text, Rails.application.config.about_text %>
  </div>

  <div>
    <%= label_tag :contact_phone, 'Contact Phone' %>
    <%= text_field_tag :contact_phone, Rails.application.config.contact_phone %>
  </div>

  <div>
    <%= label_tag :contact_email, 'Contact Email' %>
    <%= text_field_tag :contact_email, Rails.application.config.contact_email %>
  </div>

  <div>
    <%= submit_tag 'Update About Information' %>
  </div>
<% end %>

app/views/admin/admins/edit_product.html.erb
<h1 class='editp'>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back to Dashboard', products_path %>

app/views/admin/admins/new_product.html.erb
<h1 class='editp'>Add a New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back to Product Listing', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeEssentials</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <% #javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'custom' %>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to 'Home', root_path %>
  <%= link_to 'About', about_path %>

  <% if current_page?(products_path) %>
    <%= link_to 'On Sale', on_sale_products_path %>
    <%= link_to 'New Products', new_products_products_path %>
  <% end %>

  <% if logged_in? %>
    <%= link_to 'Product List', products_path %>
    <%= link_to 'Cart', cart_path %>
    <%= link_to 'Logout', logout_path %>
  <% else %>
    <%= link_to 'Login', login_path %>
  <% end %>
</nav>