config/routes.rb
Rails.application.routes.draw do
  get 'checkouts/create'
  get 'order_items/update'
  root 'home#index'

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'

  resources :products, only: [:index, :show] do
    collection do
      get 'on_sale', to: 'products#on_sale', as: 'on_sale'
      get 'new_products', to: 'products#new_products', as: 'new_products'
    end
    get 'show_category/:id', to: 'products#show_category', on: :member, as: :show_category
    get 'show_product/:id', to: 'products#show', on: :member, as: :show_product
    get 'search', on: :collection
  end

  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    get 'new_product', to: 'admins#new_product', as: 'new_product'
    post 'create_product', to: 'admins#create_product', as: 'create_product'
    get 'edit_product/:id', to: 'admins#edit_product', as: 'edit_product'
    patch 'update_product/:id', to: 'admins#update_product', as: 'update_product'
    delete 'delete_product/:id', to: 'admins#delete_product', as: 'delete_product'
    get 'edit_about', to: 'admins#edit_about', as: 'edit_about_admin'
    patch 'update_about', to: 'admins#update_about', as: 'update_about_admin'
  end

  post 'add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  resource :cart, only: [:show, :create, :destroy] do
    resources :order_items, only: [:destroy, :update], as: 'items', path: 'items'
  end
  delete 'remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  scope '/checkouts' do
  post 'create', to: 'checkouts#create', as: 'create_checkout'
  get 'success', to: 'checkouts#success', as: 'checkout_success'
  get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
  end
  get 'about', to: 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true

  has_one_attached :image
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  accepts_nested_attributes_for :categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_many :order_items, through: :orders
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :country, presence: true
  validates :province, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :street_address, presence: true
  def admin?
    admin
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login

  def show
    @order_items = current_user.order_items.includes(:product)
  end

  def remove_item
    order_item = current_user.order_items.find(params[:id])
    order_item.destroy

    redirect_to cart_path, notice: 'Item removed from the cart.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @logged_in = logged_in?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @product = Product.find(params[:id])
  end

  def show_category
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 5)
  end
  def on_sale
    @products = Product.where(on_sale: true)
  end

  def new_products
    @products = Product.where(new_product: true)
  end
  def search
    @keyword = params[:keyword]
    @products = Product.where("name LIKE ? OR description LIKE ?", "%#{@keyword}%", "%#{@keyword}%").distinct
  end
  def add_to_cart
    product_id = params[:id].to_i
    @product = Product.find(product_id)

    order = current_user.orders.find_or_create_by(status: 'in_progress')
    order_item = order.order_items.find_or_initialize_by(product: @product)

    if order_item.new_record?
      order_item.quantity = 1
    else
      order_item.quantity += 1
    end

    order_item.save

    redirect_to cart_path, notice: 'Product added to cart.'
  end
  def remove_from_cart
    product_id = params[:id].to_i
    @product = Product.find(product_id)

    order = current_user.orders.find_by(status: 'in_progress')
    order_item = order.order_items.find_by(product: @product)

    if order_item
      order_item.destroy
      redirect_to cart_path, notice: 'Product removed from cart.'
    else
      redirect_to cart_path, alert: 'Product not found in the cart.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to root_path, notice: 'Account created successfully!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :admin,
      :country,
      :province,
      :city,
      :postal_code,
      :street_address
    )
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/index.html.erb
<div class='containerP'>
  <h1>Product List</h1>

  <% if current_user && current_user.admin? %>
    <%= link_to 'Add New Product', admin_new_product_path %>
  <% end %>
  <ul class='ulp'>
    <% @categories.each do |category| %>
      <li class='lip'>
        <strong><%= link_to category.name, show_category_product_path(category) %></strong>
      </li>
    <% end %>
  </ul>
</div>

app/views/products/new_products.html.erb
<% @products.each do |product| %>
  <div class="product-container">
    <h1 class="product-heading"><%= "#{product.name} (New Product)" %></h1>

    <div>
      <% if product.image.attached? %>
        <%= image_tag url_for(product.image.variant(resize_to_limit: [200, 200])), class: 'product-image' %>
      <% end %>

      <p><strong>Description:</strong> <%= product.description %></p>
      <p><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
    </div>

    <%= button_to 'Add to Cart 🛒', add_to_cart_path(product), method: :post, class: 'add-to-cart-button' %>
  </div>
<% end %>

app/views/products/on_sale.html.erb
<% @products.each do |product| %>
  <div class="product-container">
    <h1 class="product-heading"><%= "#{product.name} (On Sale)" %></h1>

    <div>
      <% if product.image.attached? %>
        <%= image_tag url_for(product.image.variant(resize_to_limit: [200, 200])), class: 'product-image' %>
      <% end %>

      <p><strong>Description:</strong> <%= product.description %></p>
      <p><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
    </div>
    <%= button_to 'Add to Cart 🛒', add_to_cart_path(product), method: :post, class: 'add-to-cart-button' %>
  </div>
<% end %>

app/views/products/remove_from_cart.html.erb
<h1>Product Removed</h1>

<p><%= notice %></p>

<%= link_to 'Back to Cart', cart_path %>

app/views/products/search.html.erb
<div class="search-results-container">
  <h1 class="search-results-heading">Search Results</h1>

  <% if @products.any? %>
    <ul class="search-results-list">
      <% @products.each do |product| %>
        <li class="search-result-item"><%= link_to product.name, product_path(product), class: 'search-result-link' %></li>
      <% end %>
    </ul>
  <% else %>
    <p class="no-results-message">No products found for '<%= @keyword %>'</p>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="product-details-container">
  <h1 class="product-name"><%= @product.name %></h1>
  <p class="product-description">Description: <%= @product.description %></p>
  <p class="product-price">Price: <%= number_to_currency(@product.price) %></p>

  <% if @product.image.attached? %>
    <%= image_tag url_for(@product.image.variant(resize_to_limit: [200, 200])), class: 'product-image', alt: 'Product Image' %>
  <% end %>

  <%= form_tag add_to_cart_path(@product), method: :post do %>
  <%= submit_tag 'Add to Cart 🛒', class: 'add-to-cart-button' %>
  <% end %>
  <% if current_user && current_user.admin? %>
    <div class="admin-actions">
      <%= link_to 'Edit', admin_edit_product_path(@product), class: 'admin-edit-link' %>
    </div>
    <div>
      <%= form_tag admin_delete_product_path(@product), method: :delete do %>
        <%= submit_tag 'Delete', class: 'admin-delete-button' %>
      <% end %>
    </div>
  <% end %>

  <%= link_to 'Back to Product Listing', products_path, class: 'back-to-listing-link' %>
</div>

app/views/products/show_category.html.erb
<div class="product-container">
  <h1 class="product-heading">Products in <%= @category.name %> Category</h1>

  <%= form_with(url: search_products_path, method: :get, class: 'search-form') do |form| %>
    <%= form.text_field :keyword, placeholder: 'Enter keyword' %>
    <%= form.submit 'Search' %>
  <% end %>

  <ul class="product-list">
    <% @products.each do |product| %>
      <li class="product-item">
        <strong><%= link_to product.name, show_product_product_path(product), class: 'product-link' %></strong>
      </li>
    <% end %>
  </ul>

  <%= will_paginate @products %>
</div>